# -*- coding: utf-8 -*-
"""MalariaCellDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhxNC1o-IQ4OB_BFBWormamhYffwKFD9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow
from tensorflow import keras
from keras import layers
import os
import cv2
from tqdm import tqdm
from PIL import Image

np.random.seed(312)

os.environ["KERAS_BACKEND"]= 'tensorflow'
cur = os.getcwd()

img_dir = cur+"\\Malarial Cell Image Data_\\cell_images"

img_dir

dr = img_dir+"/Parasitized/C33P1thinF_IMG_20150619_114756a_cell_179.png"
dataset = []
label = []

para = os.listdir(img_dir+"\\Parasitized")
for i,image_name in enumerate(tqdm(para)):
    if (image_name.split('.')[1] == 'png'):
        image = cv2.imread(img_dir+"\\Parasitized\\"+image_name)
        image = Image.fromarray(image,'RGB')
        image = image.resize((64,64))
        dataset.append(np.array(image))
        label.append(1)

normal = os.listdir(img_dir+"\\Uninfected")

for i, image in enumerate(tqdm(normal)):
    if image.split('.')[1]== '.png':
        im = cv2.imread(img_dir+"\\Uninfected\\"+image)
        im = Image.fromarray(im,'RGB')
        im =im.resize((64,64))
        dataset.append(np.array(im))
        label.append(0)

from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

xtrain,xtest,ytrain,ytest = train_test_split(dataset , to_categorical(np.array(label)),test_size=0.2 , random_state=0)

#CNN model architecture

input_size = (64,64,3)

inp = tensorflow.keras.layers.Input(shape=input_size)
conv1 = tensorflow.keras.layers.Conv2D(32,kernel_size=(3,3),activation='relu',padding='same')(inp)
pool1 = tensorflow.keras.layers.MaxPool2D(pool_size=(2,2))(conv1)
norm1 = tensorflow.keras.layers.BatchNormalization(axis=-1)(pool1)
drop1 = tensorflow.keras.layers.Dropout(rate=0.2)(norm1)

conv2 = tensorflow.keras.layers.Conv2D(32,kernel_size=(3,3),activation='relu',padding='same')(drop1)
pool2 = tensorflow.keras.layers.MaxPool2D(pool_size=(2,2))(conv2)
norm2 = tensorflow.keras.layers.BatchNormalization(axis=-1)(pool2)
drop2 = tensorflow.keras.layers.Dropout(rate=0.2)(norm2)

flat =  tensorflow.keras.layers.Flatten()(drop2)

h1 = tensorflow.keras.layers.Dense(512,activation='relu')(flat)
norm3 = tensorflow.keras.layers.BatchNormalization(axis=-1)(h1)
drop3 = tensorflow.keras.layers.Dropout(rate=0.2)(norm3)

h2 = tensorflow.keras.layers.Dense(256,activation='relu')(drop3)
norm4 = tensorflow.keras.layers.BatchNormalization(axis=-1)(h2)
drop4 = tensorflow.keras.layers.Dropout(rate=0.2)(norm4)

h3 = tensorflow.keras.layers.Dense(128,activation='relu')(drop4)
norm5 = tensorflow.keras.layers.BatchNormalization(axis=-1)(h3)
drop5 = tensorflow.keras.layers.Dropout(rate=0.2)(norm5)

out = tensorflow.keras.layers.Dense(2 , activation='sigmoid')(drop4)

model = keras.Model(inputs = inp , outputs = out)
model.compile(optimizer='adam' ,loss='binary_crossentropy', metrics=['accuracy'] )

model.summary()

history = model.fit(np.array(xtrain),ytrain,batch_size=64,verbose=1,epochs=10,validation_split=0.1)

model.evaluate(np.array(xtest),np.array(ytest))

acc = history.history['accuracy']
loss = history.history['loss']

epochs = history.epoch

plt.subplot(2,2,1)
plt.plot(epochs,acc)
plt.xlabel('epoches')
plt.ylabel('accuracy')
plt.subplot(2,2,2)
plt.plot(epochs,loss)
plt.xlabel('epoches')
plt.ylabel('loss')
plt.show()

# Get the weights of first conv layer
weights, biases = model.layers[1].get_weights()
print(weights.shape)
# For Conv2D(32, (3,3)) on RGB input --> (3, 3, 3, 32)

